version: '2'
services:

   
#Load Balancer
 nginx:
   image: jwilder/nginx-proxy
   volumes:
     - /var/run/docker.sock:/tmp/docker.sock:ro
     - ./certs:/etc/nginx/certs
   ports:
     - 80:80
     - 443:443
   networks:
     - wpsite

#Database
 db:
   image: mysql:5.7
   volumes:
     - ./mysql:/var/lib/mysql
   restart: unless-stopped
   environment:
     MYSQL_ROOT_PASSWORD: password
     MYSQL_DATABASE: wordpress
     MYSQL_USER: wordpress
     MYSQL_PASSWORD: wordpress
   networks:
     - wpsite

#Wordpress1
 wordpress_1:
   image: wordpress
   restart: unless-stopped
   ports: 
     - 8081:80
   volumes: 
     - ./:/var/www/html
   expose:
     - 80
   environment:
     WORDPRESS_DB_HOST: db
     WORDPRESS_DB_USER: wordpress
     WORDPRESS_DB_PASSWORD: wordpress
     WORDPRESS_DB_NAME: wordpress
     VIRTUAL_HOST: parcial1.local
   networks:
     - wpsite

#Wordpress2
 wordpress_2:
   image: wordpress
   restart: unless-stopped
   ports: 
     - 8080:80 
   volumes: 
     - ./:/var/www/html
   expose:
     - 80
   environment:
     WORDPRESS_DB_HOST: db
     WORDPRESS_DB_USER: wordpress
     WORDPRESS_DB_PASSWORD: wordpress
     WORDPRESS_DB_NAME: wordpress
     VIRTUAL_HOST: parcial1.local
   networks:
     - wpsite

networks:
  wpsite:

 
