services:
    #redis
    #nginx
    #https?
    #MySQL
    db:
        image: mysql:5.7
        volumes:
        #Agregar nombre de usuario 
        - /home/<usuario>/wp_site/mysql:/var/lib/mysql
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
        networks:
        - wpsite_net

    #Wordpress 1
    
    wordpress_1:
        image: wordpress
        ports:
            - 8080:80
        restart: always
        volumes: ['./:/var/www/html']
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            WORDPRESS_DB_NAME: wordpress
        networks:
            - wpsite_net

networks:
    wpsite_net:
            
    