version: '2'
services:

   
#Load Balancer
 nginx:
   image: jwilder/nginx-proxy
   volumes:
     - /var/run/docker.sock:/tmp/docker.sock:ro
       # - ./proxy/nginx.conf:/etc/nginx/conf.d/parcial1.eastus.cloudapp.azure.com.conf:ro
     - ./certs:/etc/nginx/certs
     - /etc/nginx/vhost.d
     - /usr/share/nginx/html  
   ports:
     - 80:80
     - 443:443
   networks:
     - wpsite
   labels:
     - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy      

#SSL
 letsencrypt:
   image: jrcs/letsencrypt-nginx-proxy-companion
   restart: always
   volumes:
     - ./certs:/etc/nginx/certs:rw
     - /var/run/docker.sock:/var/run/docker.sock:ro
   volumes_from:
     - nginx:rw    

#Database
 db:
   image: mysql:5.7
   volumes:
     - ./mysql:/var/lib/mysql
   restart: always
   environment:
     MYSQL_ROOT_PASSWORD: password
     MYSQL_DATABASE: wordpress
     MYSQL_USER: wordpress
     MYSQL_PASSWORD: wordpress
   networks:
     - wpsite

#Wordpress1
 wordpress_1:
   image: wordpress
   restart: always
   ports: 
     - 8081:80
   volumes: 
     - ./:/var/www/html
   expose:
     - 80
   environment:
     WORDPRESS_DB_HOST: db
     WORDPRESS_DB_USER: wordpress
     WORDPRESS_DB_PASSWORD: wordpress
     WORDPRESS_DB_NAME: wordpress
     VIRTUAL_HOST: parcial1.eastus.cloudapp.azure.com
     LETSENCRYPT_HOST: parcial1.eastus.cloudapp.azure.com 
   networks:
     - wpsite

#Wordpress2
 wordpress_2:
   image: wordpress
   restart: always
   ports: 
     - 8080:80 
   volumes: 
     - ./:/var/www/html
   expose:
     - 80
   environment:
     WORDPRESS_DB_HOST: db
     WORDPRESS_DB_USER: wordpress
     WORDPRESS_DB_PASSWORD: wordpress
     WORDPRESS_DB_NAME: wordpress
     VIRTUAL_HOST: parcial1.eastus.cloudapp.azure.com
     LETSENCRYPT_HOST: parcial1.eastus.cloudapp.azure.com
   networks:
     - wpsite

networks:
  wpsite:

 
